# Generated by Django 5.2 on 2025-04-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('technology', models.CharField(max_length=200, verbose_name='Technology Used')),
                ('made_at', models.DateField(blank=True, verbose_name='Date of creation')),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d', verbose_name='Image')),
                ('github_link', models.URLField(blank=True, verbose_name='Github link')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.category', verbose_name='Category')),
            ],
        ),
    ]
